name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      SKIP_CONFIG_VALIDATION: 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build

      - name: Basic Runtime Smoke Test
        run: node -e "require('./dist/index.js'); console.log('Server module loads successfully');"

      - name: Run Query Tests (lightweight)
        run: npm run test:queries

      - name: Verify Build Script
        run: npm run verify-build

      - name: Artifact (optional) - Dist
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error
